### ISSUE TITLE
Data used problem

### ISSUE THREAD

**Issue by yxgz** [KevinDuarte/VideoCapsuleNet#2]
Hi, thank you for the great project. 
I wonder how many frames should be extracted from each video, and which tool should be used to extract these frames. Would you please give me more details? Thank you!

**Comment by KevinDuarte** [comment]
All frames should be extracted from each video, and downsized as stated in the "Data Used" section of the README.md file.
The way I did this was loading them into python using scikit-video to load in the video and saving each frame individually using scipy.misc.imsave().
